export const peoples = [
  {
    id: 1,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    address: {
      street: 'Kulas Light',
      city: 'Gwenborough',
      state: 'Florida',
      zipcode: '92998-3874',
    },
    departement: 'management',
    dateFirstDayIn: '03/03/2022',
  },
  {
    id: 2,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    address: {
      street: 'Victor Plains',
      city: 'Wisokyburgh',
      state: 'Utah',
      zipcode: '90566-7771',
    },
    departement: 'sales',
    dateFirstDayIn: '04/04/2022',
  },
  {
    id: 3,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    address: {
      street: 'Douglas Extension',
      city: 'McKenziehaven',
      state: 'Indiana',
      zipcode: '59590-4157',
    },
    departement: 'production',
    dateFirstDayIn: '05/05/2022',
  },
  {
    id: 4,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    address: {
      street: 'Hoeger Mall',
      city: 'South Elvis',
      state: 'Michigan',
      zipcode: '53919-4257',
    },
    departement: 'engineering',
    dateFirstDayIn: '06/06/2022',
  },
  {
    id: 5,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    address: {
      street: 'Skiles Walks',
      city: 'Roscoeview',
      state: 'Arizona',
      zipcode: '33263',
    },
    departement: 'sales',
    dateFirstDayIn: '07/07/2022',
  },
  {
    id: 6,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    address: {
      street: 'Norberto Crossing',
      city: 'South Christy',
      state: 'Colorado',
      zipcode: '23505-1337',
    },
    departement: 'engineering',
    dateFirstDayIn: '08/08/2022',
  },
  {
    id: 7,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    address: {
      street: 'Rex Trail',
      city: 'Howemouth',
      state: 'Montana',
      zipcode: '58804-1099',
    },
    departement: 'HR',
    dateFirstDayIn: '09/09/2022',
  },
  {
    id: 8,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    address: {
      street: 'Ellsworth Summit',
      city: 'Aliyaview',
      state: 'Texas',
      zipcode: '45169',
    },
    departement: 'production',
    dateFirstDayIn: '10/10/2022',
  },
  {
    id: 9,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    address: {
      street: 'Dayna Park',
      city: 'Bartholomebury',
      state: 'California',
      zipcode: '76495-3109',
    },
    departement: 'QC',
    dateFirstDayIn: '11/11/2022',
  },
  {
    id: 10,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    address: {
      street: 'Kattie Turnpike',
      city: 'Lebsackbury',
      state: 'Louisiana',
      zipcode: '31428-2261',
    },
    departement: 'production',
    dateFirstDayIn: '12/12/2022',
  },
];
