import { departments } from './utils/utils';

export const peoples = [
  {
    id: 1,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 2,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 3,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 4,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 5,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 6,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 7,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 8,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 9,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 10,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 11,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 12,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 13,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 14,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 15,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 16,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 17,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 18,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 19,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 20,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 21,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 22,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 23,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 24,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 25,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 26,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 27,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 28,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 29,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 30,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 31,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 32,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 33,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 34,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 35,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 36,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 37,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 38,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 39,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 40,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 41,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 42,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 43,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 44,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 45,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 46,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 47,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 48,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 49,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 50,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 51,
    firstname: 'Leanne',
    lastname: 'Graham',
    birthday: '01/01/1990',
    street: 'Kulas Light',
    city: 'Gwenborough',
    state: 'Florida',
    zipcode: '92998-3874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 52,
    firstname: 'Ervin',
    lastname: 'Howell',
    birthday: '02/02/1990',
    street: 'Victor Plains',
    city: 'Wisokyburgh',
    state: 'Utah',
    zipcode: '90566-7771',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 53,
    firstname: 'Clementine',
    lastname: 'Bauch',
    birthday: '03/03/1990',
    street: 'Douglas Extension',
    city: 'McKenziehaven',
    state: 'Indiana',
    zipcode: '59590-4157',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 54,
    firstname: 'Patricia',
    lastname: 'Lebsack',
    birthday: '04/04/1990',
    street: 'Hoeger Mall',
    city: 'South Elvis',
    state: 'Michigan',
    zipcode: '53919-4257',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 55,
    firstname: 'Chelsey',
    lastname: 'Dietrich',
    birthday: '05/05/1990',
    street: 'Skiles Walks',
    city: 'Roscoeview',
    state: 'Arizona',
    zipcode: '33263',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 56,
    firstname: 'Dennis',
    lastname: 'Schulist',
    birthday: '06/06/1990',
    street: 'Norberto Crossing',
    city: 'South Christy',
    state: 'Colorado',
    zipcode: '23505-1337',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 57,
    firstname: 'Kurtis',
    lastname: 'Weissnat',
    birthday: '07/07/1990',
    street: 'Rex Trail',
    city: 'Howemouth',
    state: 'Montana',
    zipcode: '58804-1099',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 58,
    firstname: 'Nicholas',
    lastname: 'Runolfsdottir',
    birthday: '08/08/1990',
    street: 'Ellsworth Summit',
    city: 'Aliyaview',
    state: 'Texas',
    zipcode: '45169',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 59,
    firstname: 'Glenna',
    lastname: 'Reichert',
    birthday: '09/09/1990',
    street: 'Dayna Park',
    city: 'Bartholomebury',
    state: 'California',
    zipcode: '76495-3109',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 60,
    firstname: 'Clementina',
    lastname: 'DuBuque',
    birthday: '10/10/1990',
    street: 'Kattie Turnpike',
    city: 'Lebsackbury',
    state: 'Louisiana',
    zipcode: '31428-2261',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
];
