import { departments } from './utils/utils';

export const peoples = [
  {
    id: 1,
    firstname: 'Lonny',
    lastname: 'Hirthe',
    birthday: '01/01/1990',
    street: 'Britney Flats',
    city: 'Sioux City',
    state: 'North Carolina',
    zipcode: '96747',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 2,
    firstname: 'Laney',
    lastname: 'Feeney',
    birthday: '02/02/1990',
    street: 'Schaefer Extension',
    city: 'Hammeshaven',
    state: 'Utah',
    zipcode: '53859-8007',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 3,
    firstname: 'Tomasa',
    lastname: 'Gorczany',
    birthday: '03/03/1990',
    street: 'Jakubowski Island',
    city: 'North Kaileystad',
    state: 'Oregon',
    zipcode: '88910',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 4,
    firstname: 'Lexie',
    lastname: 'Moore',
    birthday: '04/04/1990',
    street: 'Everardo Rest',
    city: 'Troy',
    state: 'Montana',
    zipcode: '37875',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 5,
    firstname: 'Orion',
    lastname: 'Adams',
    birthday: '05/05/1990',
    street: 'Ron Spring',
    city: 'West Carolyneshire',
    state: 'Texas',
    zipcode: '00180',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 6,
    firstname: 'Noelia',
    lastname: 'Franecki',
    birthday: '06/06/1990',
    street: 'Howe Passage',
    city: 'Kierafort',
    state: 'Wisconsin',
    zipcode: '53491',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 7,
    firstname: 'Elliot',
    lastname: 'Bauch',
    birthday: '07/07/1990',
    street: 'Myrtle Street',
    city: 'East Onie',
    state: 'Georgia',
    zipcode: '83432-4379',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 8,
    firstname: 'Parker',
    lastname: 'Heaney',
    birthday: '08/08/1990',
    street: 'Kris Prairie',
    city: 'East Velmamouth',
    state: 'Wisconsin',
    zipcode: '45515-8540',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 9,
    firstname: 'Enrico',
    lastname: 'Friesen',
    birthday: '09/09/1990',
    street: 'Lucius Lock',
    city: 'New Xzavier',
    state: 'Oklahoma',
    zipcode: '00292-4057',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 10,
    firstname: 'Judd',
    lastname: 'Bahringer',
    birthday: '10/10/1990',
    street: 'Christiansen Burg',
    city: 'Georgetown',
    state: 'Pennsylvania',
    zipcode: '44247-2429',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 11,
    firstname: 'Kraig',
    lastname: 'Kuhn',
    birthday: '01/01/1990',
    street: 'Larue Islands',
    city: 'Brentwood',
    state: 'Louisiana',
    zipcode: '44095',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 12,
    firstname: 'Willie',
    lastname: 'McLaughlin',
    birthday: '02/02/1990',
    street: 'Geraldine Wells',
    city: 'Trevionhaven',
    state: 'Rhode Island',
    zipcode: '79025-5171',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 13,
    firstname: 'Ellie',
    lastname: 'Fay',
    birthday: '03/03/1990',
    street: 'Jackeline Village',
    city: 'Visalia',
    state: 'Oklahoma',
    zipcode: '55960-5702',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 14,
    firstname: 'Stevie',
    lastname: 'Hackett',
    birthday: '04/04/1990',
    street: 'Jefferey Ports',
    city: 'Corpus Christi',
    state: 'Ohio',
    zipcode: '37710',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 15,
    firstname: 'Mia',
    lastname: 'Kassulke',
    birthday: '05/05/1990',
    street: 'Dickens Hill',
    city: 'Port Nigel',
    state: 'Michigan',
    zipcode: '30745',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 16,
    firstname: 'Davion',
    lastname: 'Sipes',
    birthday: '06/06/1990',
    street: 'Brain Trail',
    city: 'East Alessandro',
    state: 'Illinois',
    zipcode: '39399',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 17,
    firstname: 'Wellington',
    lastname: 'Doyle',
    birthday: '07/07/1990',
    street: 'Toy Points',
    city: 'Marysville',
    state: 'Maryland',
    zipcode: '60454',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 18,
    firstname: 'Opal',
    lastname: 'Wolff',
    birthday: '08/08/1990',
    street: 'Serena Mountains',
    city: 'Kertzmannshire',
    state: 'Arkansas',
    zipcode: '97574-0921',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 19,
    firstname: 'Deondre',
    lastname: 'Hagenes',
    birthday: '09/09/1990',
    street: 'Wolf Route',
    city: 'Lakewood',
    state: 'Florida',
    zipcode: '35602-7512',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 20,
    firstname: 'Donald',
    lastname: 'Steuber',
    birthday: '10/10/1990',
    street: 'Destini Harbor',
    city: 'Anabelburgh',
    state: 'South Carolina',
    zipcode: '15034-6618',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 21,
    firstname: 'Kamille',
    lastname: 'Prosacco',
    birthday: '01/01/1990',
    street: 'Monahan Avenue',
    city: 'McDermottton',
    state: 'Vermont',
    zipcode: '63413',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 22,
    firstname: 'Autumn',
    lastname: 'Kiehn',
    birthday: '02/02/1990',
    street: 'Beer Station',
    city: 'South Zoey',
    state: 'Oklahoma',
    zipcode: '03977',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 23,
    firstname: 'Ferne',
    lastname: 'Yost',
    birthday: '03/03/1990',
    street: 'Trinity Glens',
    city: 'Greenfurt',
    state: 'Wisconsin',
    zipcode: '81544-3236',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 24,
    firstname: 'Renee',
    lastname: 'Abernathy',
    birthday: '04/04/1990',
    street: 'Kessler Mountains',
    city: 'Friedrichberg',
    state: 'Pennsylvania',
    zipcode: '64874',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 25,
    firstname: 'Diana',
    lastname: 'Moore',
    birthday: '05/05/1990',
    street: 'Collins Highway',
    city: 'South Dante',
    state: 'New York',
    zipcode: '79095',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 26,
    firstname: 'Enrico',
    lastname: 'Crona',
    birthday: '06/06/1990',
    street: 'Amos Drive',
    city: 'Lake Delfina',
    state: 'Utah',
    zipcode: '87802',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 27,
    firstname: 'Terrence',
    lastname: 'Stracke',
    birthday: '07/07/1990',
    street: 'Kautzer Haven',
    city: 'East Sandy',
    state: 'Nebraska',
    zipcode: '30666-0692',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 28,
    firstname: 'Reanna',
    lastname: 'Aufderhar',
    birthday: '08/08/1990',
    street: 'Prohaska Mall',
    city: 'North Delbert',
    state: 'South Carolina',
    zipcode: '22346-8035',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 29,
    firstname: 'Cielo',
    lastname: 'Moore',
    birthday: '09/09/1990',
    street: 'Ruecker Radial',
    city: 'Connellyton',
    state: 'Nebraska',
    zipcode: '33553-1690',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 30,
    firstname: 'Graham',
    lastname: 'Hansen',
    birthday: '10/10/1990',
    street: 'Hackett Cliff',
    city: 'Jedport',
    state: 'Idaho',
    zipcode: '22503-6963',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 31,
    firstname: 'Kelsie',
    lastname: 'Stehr',
    birthday: '01/01/1990',
    street: 'Weldon Expressway',
    city: 'West Nella',
    state: 'Georgia',
    zipcode: '38244',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 32,
    firstname: 'Omer',
    lastname: 'Rath',
    birthday: '02/02/1990',
    street: 'Ruecker Court',
    city: 'Bogisichborough',
    state: 'West Virginia',
    zipcode: '28927-2672',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 33,
    firstname: 'Bryce',
    lastname: 'Howe',
    birthday: '03/03/1990',
    street: 'Lionel Centers',
    city: 'Francesberg',
    state: 'Mississippi',
    zipcode: '70494',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 34,
    firstname: 'Della',
    lastname: 'Koch',
    birthday: '04/04/1990',
    street: 'Kovacek Mission',
    city: 'Briaville',
    state: 'Idaho',
    zipcode: '33935-5797',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 35,
    firstname: 'Rossie',
    lastname: 'McClure',
    birthday: '05/05/1990',
    street: 'Katelynn Roads',
    city: 'Allieland',
    state: 'California',
    zipcode: '69722-3790',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 36,
    firstname: 'Faye',
    lastname: 'Koelpin',
    birthday: '06/06/1990',
    street: 'Pat Center',
    city: 'Cicero',
    state: 'Pennsylvania',
    zipcode: '46446',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 37,
    firstname: 'Casimer',
    lastname: 'Ondricka',
    birthday: '07/07/1990',
    street: 'Lang Expressway',
    city: 'St. George',
    state: 'Nebraska',
    zipcode: '27187',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 38,
    firstname: 'Nils',
    lastname: 'Moen',
    birthday: '08/08/1990',
    street: 'Koepp Orchard',
    city: 'Sydneyborough',
    state: 'South Carolina',
    zipcode: '16472-4360',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 39,
    firstname: 'Kane',
    lastname: 'Mante',
    birthday: '09/09/1990',
    street: 'Aglae Court',
    city: 'Port Pasqualefort',
    state: 'Wyoming',
    zipcode: '58327-4023',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 40,
    firstname: 'Chester',
    lastname: 'Kuvalis',
    birthday: '10/10/1990',
    street: 'Adams Crescent',
    city: 'Hamillmouth',
    state: 'Wisconsin',
    zipcode: '21528-4695',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 41,
    firstname: 'Dakota',
    lastname: 'Wunsch',
    birthday: '01/01/1990',
    street: 'Reinger Mountain',
    city: 'Alexandriachester',
    state: 'New Hampshire',
    zipcode: '10762-6370',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 42,
    firstname: 'Frida',
    lastname: 'Wolff',
    birthday: '02/02/1990',
    street: 'Simonis View',
    city: 'East Delfinamouth',
    state: 'New Hampshire',
    zipcode: '29118-2250',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 43,
    firstname: 'Ashley',
    lastname: 'Skiles',
    birthday: '03/03/1990',
    street: 'Lelah Road',
    city: 'McKenzieland',
    state: 'Oregon',
    zipcode: '68910',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 44,
    firstname: 'Dejon',
    lastname: 'Willms',
    birthday: '04/04/1990',
    street: 'Graham Loop',
    city: 'Roswell',
    state: 'Missouri',
    zipcode: '88796-3659',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 45,
    firstname: 'Taryn',
    lastname: 'Torp',
    birthday: '05/05/1990',
    street: 'Judah Plaza',
    city: 'Bartolettiland',
    state: 'Washington',
    zipcode: '84034',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 46,
    firstname: 'Myriam',
    lastname: 'Ryan',
    birthday: '06/06/1990',
    street: 'Nickolas Ville',
    city: 'North Cadenshire',
    state: 'Utah',
    zipcode: '48219-9402',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 47,
    firstname: 'Jaylon',
    lastname: 'Cruickshank',
    birthday: '07/07/1990',
    street: 'Welch Manor',
    city: 'East Maryjanefort',
    state: 'Michigan',
    zipcode: '23833-6537',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 48,
    firstname: 'Derick',
    lastname: 'Kunde',
    birthday: '08/08/1990',
    street: 'Pollich Manor',
    city: 'Breanachester',
    state: 'Hawaii',
    zipcode: '52034',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 49,
    firstname: 'Antonina',
    lastname: 'Kautzer',
    birthday: '09/09/1990',
    street: 'Kunze Field',
    city: 'Shoreline',
    state: 'Pennsylvania',
    zipcode: '58432-6280',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 50,
    firstname: 'Salvatore',
    lastname: 'Pollich',
    birthday: '10/10/1990',
    street: 'Lura Land',
    city: 'Port Lisa',
    state: 'New Hampshire',
    zipcode: '88794',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
  {
    id: 51,
    firstname: 'Markus',
    lastname: 'Kuvalis',
    birthday: '01/01/1990',
    street: 'Rowe Cliff',
    city: 'Cartertown',
    state: 'Massachusetts',
    zipcode: '53219-9849',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '03/03/2022',
  },
  {
    id: 52,
    firstname: 'Madge',
    lastname: 'Rice',
    birthday: '02/02/1990',
    street: 'Hollie Extension',
    city: 'Port Augustineport',
    state: 'Wisconsin',
    zipcode: '41375-9706',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '04/04/2022',
  },
  {
    id: 53,
    firstname: 'Reyna',
    lastname: 'Orn',
    birthday: '03/03/1990',
    street: 'Norene Park',
    city: 'West Ansel',
    state: 'Minnesota',
    zipcode: '46120',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '05/05/2022',
  },
  {
    id: 54,
    firstname: 'Emerson',
    lastname: 'Johnson',
    birthday: '04/04/1990',
    street: 'Santino Avenue',
    city: 'Reesetown',
    state: 'Connecticut',
    zipcode: '10080',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '06/06/2022',
  },
  {
    id: 55,
    firstname: 'Belle',
    lastname: 'Durgan',
    birthday: '05/05/1990',
    street: 'Orion Loaf',
    city: 'North Caterina',
    state: 'Maryland',
    zipcode: '33532-5266',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '07/07/2022',
  },
  {
    id: 56,
    firstname: 'Olen',
    lastname: 'Heathcote',
    birthday: '06/06/1990',
    street: 'MacGyver Track',
    city: 'Palmdale',
    state: 'Minnesota',
    zipcode: '38097',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '08/08/2022',
  },
  {
    id: 57,
    firstname: 'Rubie',
    lastname: 'Wehner',
    birthday: '07/07/1990',
    street: 'Bernardo Gateway',
    city: 'New Emory',
    state: 'North Carolina',
    zipcode: '72742',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '09/09/2022',
  },
  {
    id: 58,
    firstname: 'Delphine',
    lastname: 'Reilly',
    birthday: '08/08/1990',
    street: 'Nannie Island',
    city: 'Nolanview',
    state: 'Vermont',
    zipcode: '00330',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '10/10/2022',
  },
  {
    id: 59,
    firstname: 'Stuart',
    lastname: 'Feest',
    birthday: '09/09/1990',
    street: 'Kaylie Pike',
    city: 'North Ford',
    state: 'New Hampshire',
    zipcode: '62015',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '11/11/2022',
  },
  {
    id: 60,
    firstname: 'Brandy',
    lastname: 'Champlin',
    birthday: '10/10/1990',
    street: 'Madisen Overpass',
    city: 'Cummingsstad',
    state: 'New York',
    zipcode: '15764-6776',
    departement:
      departments.names[Math.floor(Math.random() * departments.names.length)],
    firstDayIn: '12/12/2022',
  },
];
